# Generated by Django 4.1.1 on 2022-11-16 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('outdoor', 'outdoor'), ('emergency', 'emergency'), ('blood test', 'blood test'), ('urine test', 'urin test'), ('ultrasonography', 'ultrasonography'), ('pregnancy test', 'pregnancy test'), ('angiography', 'angiography'), ('echocardiography', 'echocardiography'), ('autopsy', 'autopsy'), ('biopsy', 'biopsy'), ('endoscopy', 'endoscopy'), ('chemotherapy', 'chemotherapy')], max_length=20)),
                ('apointment_day', models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thusday', 'thusday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=20)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_request_to_doctor', to='recruiters.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_request_patient', to='patient.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_summery', models.TextField(blank=True, null=True)),
                ('doctors_opinion', models.TextField(blank=True, null=True)),
                ('medicin_provide', models.TextField(blank=True, null=True)),
                ('medical_test', models.TextField(blank=True, null=True)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='recruiters.profile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_request_id', to='activities.servicesrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AdmitedPatitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('general medicine', 'general medicine'), ('surgery', 'surgery'), ('dermatology', 'dermatology'), ('nurosurgery', 'nurosurgery'), ('cardiology', 'cardiology'), ('psychiatry', 'psychiatry'), ('radiology', 'radiology'), ('pediatric surgery', 'pediatric surgery'), ('ICCU', 'ICCU'), ('CCU', 'CCU'), ('general', 'general')], max_length=20)),
                ('bed_number', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('A2', 'A2'), ('B2', 'B2'), ('A3', 'A3'), ('B3', 'B3'), ('A4', 'A4'), ('B4', 'B4'), ('A5', 'A5'), ('B5', 'B5'), ('A6', 'A6'), ('B6', 'B6'), ('A7', 'A7'), ('B7', 'B7'), ('A8', 'A8'), ('B8', 'B8'), ('A9', 'A9'), ('B9', 'B9'), ('A10', 'A10'), ('B10', 'B10')], max_length=5)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admited_patient', to=settings.AUTH_USER_MODEL)),
                ('under_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_doctor', to='recruiters.profile')),
            ],
        ),
    ]
