# Generated by Django 4.1.1 on 2022-11-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('activities', '0002_alter_admitedpatitent_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='patient.customerprofile'),
        ),
    ]
