# Generated by Django 4.1.1 on 2022-11-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_diagnosticreport_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitedpatitent',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
